### ISSUE TITLE
Parent/Child mapping

### ISSUE THREAD

**Issue by M0dM** [jaddison/django-simple-elasticsearch#10] opened 2016-02-13 22:39 UTC
Hi,

Is there any wait to deal with parent/child relationship using this app.
I need to do something like this : 
https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html

If it's not possible to do it yet could you please give me some description of the files inside the project and I will try to implement it in a pull request.

M0dM

**Comment by M0dM** [comment] 2016-02-13 23:11
Ok, I think I've got the way of doing this easilly.

What do you think about this @jaddison ?

We can add two new class method called get_parent_name and get_parent_id.
- get_parent_name return None if not defined inside user projet model using @classmethod annotation like get_index_name and get_type_name
- Inside index_add and index_add_or_delete we will juste need to test if get_parent_name is not None
- If it's the case, we can just index using the same index method from elasticsearch-py but with this parameter : 
`parent – ID of the parent document`

Anyway I will try to implement this tomorrow if I find some time.
I will maybe need some help on unit testing.

**Comment by jaddison** [comment] 2016-02-13 23:48
I currently have a project with a parent/child mapping using this app. No special methods are required - just two steps: 

1. you need to identify the parent doctype when specifying the child doc type mapping - simply add a `_parent` field definition in your child doctype mapping, at the same level as `properties` - https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html
2. you need to specify the parent doc id when indexing an child doc - you do this via the `get_request_params()` method, which adds the `parent` query string parameter to the URL request - https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html#indexing-parent-child

For example:
```
    @classmethod
    def get_type_mapping(cls):
        return {
            '_parent': {
                'type': 'my_parent_doctype'
            },
            'properties': {
                # define your fields here
            }
        }

    @classmethod
    def get_request_params(cls, obj):
        return {'parent': obj.my_parent_obj_id}
```

`get_request_params()` is also used in bulk indexing, so parent/child relationships work in both single as well as bulk indexing scenarios.

Closing this as it is not a bug or missing feature. Thanks for the interest in the project! FYI, I am updating this project to work with more recent/upcoming versions of Django; I am also ripping out the search form and elasticsearch-dsl bits (they added unnecessary complexity), so there will be some backward incompatibilies.

**Closed by jaddison** 2016-02-13 23:48 UTC

**Comment by M0dM** [comment] 2016-02-14 21:12
Tanks for the quick answer.
I really enjoy what you did with this lib from know by keeping it simple and easy to configure.
